## EXPERIMENT SPECIFIC
# [experiment]

## NEW METRICS (uncomment below)
<<<<<<< HEAD
# [metrics]
=======
[metrics]
weekly = ["opened_private_window", "days_opening_private_window"]
overall = ["opened_private_window", "days_opening_private_window"]


[metrics.opened_private_window]
data_source = "clients_daily"
select_expression = "MAX(dom_parentprocess_private_window_used)"

[metrics.opened_private_window.statistics.binomial]


[metrics.days_opening_private_window] 
data_source = "clients_daily"
select_expression = "COALESCE(SUM(CAST(dom_parentprocess_private_window_used AS int)),0)"

[metrics.days_opening_private_window.statistics.bootstrap_mean]
drop_highest = 0.0
>>>>>>> 119229c9c699b769870268c33afc726a7f86697b

## New data sources to support new metrics