[experiment]

[metrics]
daily = ["cold_main_app_to_first_frame", "cold_view_app_to_first_frame"]

weekly = ["cold_main_app_to_first_frame", "cold_view_app_to_first_frame"]

overall = ["cold_main_app_to_first_frame", "cold_view_app_to_first_frame"]

[metrics.cold_main_app_to_first_frame]
friendly_name = "Cold Main App to First Frame"
description = "The duration from application's initializer to the first Android frame being drawn in a COLD MAIN start up"
select_expression = "1.0 * SUM(metric_sum) / SUM(samples) AS metric_avg"
data_source = "cold_main_app_to_first_frame"   
statistics = { bootstrap_mean = {}, deciles = {} }

[data_sources.cold_main_app_to_first_frame]
from_expression = """(
  SELECT
    DATE(submission_timestamp) AS submission_date,
    client_info.client_id,
    AVG(metrics.timing_distribution.perf_startup_cold_main_app_to_first_frame.sum) AS metric_sum,
    SUM(m.value) AS samples
  FROM
    `mozdata.fenix.metrics`
  CROSS JOIN
    UNNEST (metrics.timing_distribution.perf_startup_cold_main_app_to_first_frame.values) m
  WHERE
    metrics.timing_distribution.perf_startup_cold_main_app_to_first_frame IS NOT NULL
  GROUP BY 1, 2
)"""

[metrics.cold_view_app_to_first_frame]
friendly_name = "Cold View App to First Frame"
description = "The duration from application's initializer to the first Android frame being drawn in a COLD VIEW start up"
select_expression = "1.0 * SUM(metric_sum) / SUM(samples) AS metric_avg"
data_source = "cold_view_app_to_first_frame"   
statistics = { bootstrap_mean = {}, deciles = {} }

[data_sources.cold_view_app_to_first_frame]
from_expression = """(
  SELECT
    DATE(submission_timestamp) AS submission_date,
    client_info.client_id,
    AVG(metrics.timing_distribution.perf_startup_cold_view_app_to_first_frame.sum) AS metric_sum,
    SUM(m.value) AS samples
  FROM
    `mozdata.fenix.metrics`
  CROSS JOIN
    UNNEST (metrics.timing_distribution.perf_startup_cold_view_app_to_first_frame.values) m
  WHERE
    metrics.timing_distribution.perf_startup_cold_view_app_to_first_frame IS NOT NULL
  GROUP BY 1, 2
)"""
