# experiment: android-nightly-sponsored-tiles-validation
[experiment]


# interested in users who are eligible for treatment in both branches: those that open homescreen
# also interested in retention rates for new users
segments = ["opened_homescreen", "new_or_resurrected_v3"]

[segments.data_sources.events_unnested]
from_expression = """(
  SELECT
    *
  FROM
    `mozdata.fenix.events_unnested`
)"""
window_start = 0
window_end = 28 

[segments.opened_homescreen]
select_expression = """
  COALESCE(CAST(MAX(
    CASE WHEN event_category = 'home_screen'
           AND event_name = 'home_screen_displayed'
         THEN 1
         ELSE 0
    END
  ) AS BOOL), FALSE)
"""
data_source = "events_unnested"



[metrics]
daily = ["spoc_tiles_impressions", "spoc_tiles_clicks", "spoc_tiles_disable_rate",
	"pocket_impressions", "pocket_clicks"]
weekly = ["spoc_tiles_impressions", "spoc_tiles_clicks", "spoc_tiles_disable_rate",
	"pocket_impressions", "pocket_clicks"]
overall = ["spoc_tiles_impressions", "spoc_tiles_clicks", "spoc_tiles_disable_rate",
	"pocket_story_impressions", "pocket_story_clicks"]



### Sponsored Tiles Metrics

[metrics.spoc_tiles_impressions]
friendly_name = "Sponsored Tiles Impressions"
description = "Number of times Contile Sponsored Tiles are shown."
select_expression = """
      COUNTIF(
          event_category = 'top_sites'
          AND event_name = 'contile_impression'
      )
"""
data_source = "events"   
[metrics.pocket_story_impressions.statistics.bootstrap_mean]
[metrics.pocket_story_impressions.statistics.deciles]

[metrics.spoc_tiles_clicks]
friendly_name = "Sponsored Tiles Clicks"
description = "Number of times user clicked a Contile Sponsored Tile."
select_expression = """
      COUNTIF(
          event_category = 'top_sites'
          AND event_name = 'contile_click'
      )
"""
data_source = "events" 
[metrics.pocket_story_clicks.statistics.bootstrap_mean]
[metrics.pocket_story_clicks.statistics.deciles]


[metrics.spoc_tiles_disable_rate]
select_expression = """   
  MAX(
    CAST(
       metrics.boolean.customize_home_contile AS int )
  )
"""
data_source = "metrics" 
bigger_is_better = false
friendly_name = "Sponsored Tiles Disable Rate"
description = "Fraction of users who disable Contile Sponsored Tiles"
[metrics.spoc_tiles_disable_rate.statistics.binomial]




### Pocket Metrics

[metrics.pocket_story_impressions]
friendly_name = "Pocket Impressions"
description = "Number of times Pocket recommended stories are shown on the home screen."
select_expression = """
      COUNTIF(
          event_category = 'pocket'
          AND event_name = 'home_recs_shown'
      )
"""
data_source = "events"   
[metrics.pocket_story_impressions.statistics.bootstrap_mean]
[metrics.pocket_story_impressions.statistics.deciles]

[metrics.pocket_story_clicks]
friendly_name = "Pocket Story Clicks"
description = "Number of times user tapped a Pocket recommended story to be opened."
select_expression = """
      COUNTIF(
          event_category = 'pocket'
          AND event_name = 'home_recs_story_clicked'
      )
"""
data_source = "events" 
[metrics.pocket_story_clicks.statistics.bootstrap_mean]
[metrics.pocket_story_clicks.statistics.deciles]
