# experiment: android-nightly-sponsored-tiles-validation
[experiment]


# interested in users who are eligible for treatment in both branches: those that open homescreen
# also interested in retention rates for new users
segments = ["opened_homescreen"] #, "new_or_resurrected_fenix"]

[segments.data_sources.events_unnested]
from_expression = """(
  SELECT
    client_info.client_id as client_id,
    CAST(submission_timestamp as DATE) as submission_date,
    *
  FROM
    `mozdata.fenix.events_unnested`
)"""
window_start = 0
window_end = 28 

[segments.opened_homescreen]
select_expression = """
  COALESCE(CAST(MAX(
    CASE WHEN event_category = 'home_screen'
           AND event_name = 'home_screen_displayed'
         THEN 1
         ELSE 0
    END
  ) AS BOOL), FALSE)
"""
data_source = "events_unnested"


[metrics]
daily = ["new_profile_retention",
	"spoc_tiles_impressions", "spoc_tiles_clicks", "spoc_tiles_disable_rate",
	"pocket_story_impressions", "pocket_story_clicks"]

weekly = ["new_profile_retention",
	"spoc_tiles_impressions", "spoc_tiles_clicks", "spoc_tiles_disable_rate",
	"pocket_story_impressions", "pocket_story_clicks"]

overall = ["retained", "new_profile_retention",
	"spoc_tiles_impressions", "spoc_tiles_clicks", "spoc_tiles_disable_rate",
	"pocket_story_impressions", "pocket_story_clicks"]

### New Profile Retention

[metrics.new_profile_retention]
friendly_name = "New Profile Retention"
description = "New profiles defined as those first seen during the first week (enrollment period) of the experiment."
select_expression = "COALESCE(COUNT(
	CASE WHEN PARSE_DATETIME('%Y %m %d %H:%M', REPLACE(REPLACE(client_info.first_run_date, '+', ' '), '-', ' ')) between '2022-03-16' and '2022-03-22'
	THEN document_id ELSE NULL END), 0) > 0"
data_source = "baseline"
[metrics.new_profile_retention.statistics.binomial]



### Sponsored Tiles Metrics

[metrics.spoc_tiles_impressions]
friendly_name = "Sponsored Tiles Impressions"
description = "Number of times Contile Sponsored Tiles are shown."
select_expression = """
      COUNTIF(
          event.category = 'top_sites'
          AND event.name = 'contile_impression'
      )
"""
data_source = "events"   
statistics = { bootstrap_mean = {}, deciles = {} }


[metrics.spoc_tiles_clicks]
friendly_name = "Sponsored Tiles Clicks"
description = "Number of times user clicked a Contile Sponsored Tile."
select_expression = """
      COUNTIF(
          event.category = 'top_sites'
          AND event.name = 'contile_click'
      )
"""
data_source = "events" 
statistics = { bootstrap_mean = {}, deciles = {} }


[metrics.spoc_tiles_disable_rate]
select_expression = """   
  MAX(
    CAST(
       metrics.boolean.customize_home_contile AS int )
  )
"""
data_source = "metrics" 
bigger_is_better = false
friendly_name = "Sponsored Tiles Disable Rate"
description = "Fraction of users who disable Contile Sponsored Tiles"
[metrics.spoc_tiles_disable_rate.statistics.binomial]




### Pocket Metrics

[metrics.pocket_story_impressions]
friendly_name = "Pocket Impressions"
description = "Number of times Pocket recommended stories are shown on the home screen."
select_expression = """
      COUNTIF(
          event.category = 'pocket'
          AND event.name = 'home_recs_shown'
      )
"""
data_source = "events"  
statistics = { bootstrap_mean = {}, deciles = {} } 


[metrics.pocket_story_clicks]
friendly_name = "Pocket Story Clicks"
description = "Number of times user tapped a Pocket recommended story to be opened."
select_expression = """
      COUNTIF(
          event.category = 'pocket'
          AND event.name = 'home_recs_story_clicked'
      )
"""
data_source = "events" 
statistics = { bootstrap_mean = {}, deciles = {} }
