[experiment]
segments = ["regular_users_v3", "new_or_resurrected_v3"]

[metrics]
weekly = ["is_default_browser"]
overall = ["is_default_browser"]

[metrics.is_default_browser]
select_expression = "ANY_VALUE( LAST_VALUE(is_default_browser) OVER (PARTITION BY clients_daily.client_id ORDER BY clients_daily.submission_date) )"
data_source = "clients_daily"

[metrics.is_default_browser.statistics.binomial]
