# https://experimenter.services.mozilla.com/experiments/pre-xul-skeleton-ui-and-abouthome-startup-cache-startup-improvement-experiment/
# Targets existing users

[experiment]
segments = ["low_cpu", "better_cpu", "hdd", "ssd"]

metrics.weekly = ["num_enrollments"]
metrics.overall = ["num_enrollments"]

[metrics.num_enrollments]
select_expression = """
    COUNT(DISTINCT
        IF(
            event_method = "enroll"
                AND event_string_value = "bug-1689450-pref-pre-xul-skeleton-ui-startup-improvement-experimen-release-86-90",
            mozfun.map.get_key(event_map_values, "enrollmentId"),
            NULL
        )
    )"""
data_source = "normandy_events"

[segments.low_cpu]
select_expression = 'COALESCE(MAX(cpu_count) BETWEEN 1 AND 2, FALSE)'
data_source = "clients_last_seen"

[segments.better_cpu]
select_expression = 'NOT COALESCE(MAX(cpu_count) BETWEEN 1 AND 2, FALSE)'
data_source = "clients_last_seen"

[segments.hdd]
select_expression = "COALESCE(ANY_VALUE(hdd_type) = 'HDD', FALSE)"
data_source = "events"

[segments.ssd]
select_expression = "COALESCE(ANY_VALUE(hdd_type) = 'SSD', FALSE)"
data_source = "events"

[segments.data_sources.events]
from_expression = """
    (SELECT
        DATE(submission_timestamp) AS submission_date,
        client_id,
        environment.system.hdd.profile.type AS hdd_type,
    FROM `moz-fx-data-shared-prod`.telemetry.event)
    """

