[experiment]
end_date = '2020-09-08'

[metrics]
overall = ['mean_page_load_time', 'mean_first_paint_time', 'mean_trr_lookup_time']

[metrics.mean_page_load_time]
select_expression = '{{agg_histogram_mean("payload.histograms.fx_page_load_ms_2")}}'
data_source = 'main'

[metrics.mean_page_load_time.statistics.bootstrap_mean]
pre_treatments = ["remove_nulls"]

[metrics.mean_page_load_time.statistics.deciles]
pre_treatments = ["remove_nulls"]

[metrics.mean_first_paint_time]
select_expression = '{{agg_histogram_mean("payload.histograms.time_to_first_contentful_paint_ms")}}'
data_source = 'main'

[metrics.mean_first_paint_time.statistics.bootstrap_mean]
pre_treatments = ["remove_nulls"]

[metrics.mean_first_paint_time.statistics.deciles]
pre_treatments = ["remove_nulls"]

[metrics.mean_trr_lookup_time]
select_expression = """\
    SAFE_DIVIDE(
        SUM((SELECT SUM(CAST(JSON_EXTRACT_SCALAR(value, "$.sum") AS int64)) FROM UNNEST(payload.keyed_histograms.dns_trr_lookup_time2))),
        SUM((SELECT SUM(mozfun.hist.threshold_count(value, 0)) FROM UNNEST(payload.keyed_histograms.dns_trr_lookup_time2)))
    )
    """
data_source = 'main'

[metrics.mean_trr_lookup_time.statistics.bootstrap_mean]
pre_treatments = ["remove_nulls"]

[metrics.mean_trr_lookup_time.statistics.deciles]
pre_treatments = ["remove_nulls"]
