# experiment: firefox-android-sponsored-shortcuts-experiment
# launched May 10, 2022
[experiment]


# interested in users who are eligible for treatment in both branches: those that open homescreen
# these users also need to be in the countries where advertisements are live
segments = ["opened_homescreen_in_live_countries"] 

[segments.data_sources.events_unnested]
from_expression = """(
  SELECT
    client_info.client_id as client_id,
    CAST(submission_timestamp as DATE) as submission_date,
    *
  FROM
    `mozdata.fenix.events_unnested`
)"""
window_start = 0
window_end = 28 

[segments.opened_homescreen_in_live_countries]
select_expression = """
  COALESCE(CAST(MAX(
    CASE WHEN event_category = 'home_screen'
           AND event_name = 'home_screen_displayed' 
	         AND metadata.geo.country IN ('US', 'GB', 'DE', 'FR', 'AU', 'CA', 'ES', 'IT', 'IN', 'JP', 'BR', 'MX')
         THEN 1
         ELSE 0
    END
  ) AS BOOL), FALSE)
"""
data_source = "events_unnested"

[metrics]
daily = ["new_profile_retention"]

weekly = ["new_profile_retention"]


### New Profile Retention

[metrics.new_profile_retention]
friendly_name = "New Profile Retention"
description = "New profiles defined as those first seen during the first week (enrollment period) of the experiment."
select_expression = """COALESCE(COUNT(
	CASE WHEN PARSE_DATETIME('%Y %m %d %H:%M', REPLACE(REPLACE(client_info.first_run_date, '+', ' '), '-', ' ')) between '2022-04-06' and '2022-04-12'
	THEN document_id ELSE NULL END), 0) > 0
"""
data_source = "baseline"
[metrics.new_profile_retention.statistics.binomial]
