[experiment]
end_date = "2022-08-05"

[metrics]
overall = ["new_profile_activation"]

[metrics.new_profile_activation]
data_source = "new_profile_activation"
select_expression = "SUM(activated) / SUM(new_profile)"


[data_sources]

[data_sources.new_profile_activation]
from_expression = "`moz-fx-data-shared-prod.firefox_ios.new_profile_activation`"
experiments_column_type = "none"
