{\rtf1\ansi\ansicpg1252\cocoartf2580
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 [experiment]\
segments = ['urlbar_users', 'searchsuggestion_users']\
\
[segments.urlbar_users]\
select_expression = 'COALESCE(LOGICAL_OR((events.key like "urlbar#%#%") AND (events.value > 0)), FALSE)'\
data_source = "clients_daily_unnested"\
\
[segments.data_sources.clients_daily_unnested]\
from_expression = """(\
  SELECT \
    submission_date,\
    client_id,\
    events\
  FROM\
    `moz-fx-data-shared-prod`.telemetry.clients_daily\
  CROSS JOIN\
    UNNEST(scalar_parent_telemetry_event_counts_sum) AS events\
)"""\
window_start = -7\
window_end = 0\
\
[segments.searchsuggestion_users]\
select_expression = """\
  COALESCE((SUM(COALESCE((\
    SELECT SUM(x.value) FROM UNNEST(scalar_parent_urlbar_picked_searchsuggestion_sum\
  ) x), 0)) > 0), FALSE)\
"""\
data_source = "clients_daily_custom_windows"\
\
[segments.data_sources.clients_daily_custom_windows]\
from_expression = "mozdata.telemetry.clients_daily"\
window_start = -7\
window_end = 0\
\
[metrics]\
weekly = [\
	"urlbar_search_count", \
	"autofill_count", \
	"bookmark_count", \
	"formhistory_count", \
	"history_count", \
	"searchengine_count", \
	"searchsuggestion_count", \
	"topsite_count", \
	"visiturl_count", \
	"unknown_count"\
]\
overall = [\
	"urlbar_search_count", \
	"autofill_count", \
	"bookmark_count", \
	"formhistory_count", \
	"history_count", \
	"searchengine_count", \
	"searchsuggestion_count", \
	"topsite_count", \
	"visiturl_count", \
	"unknown_count"\
]\
\
\
}